#
# DO NOT EDIT THIS FILE DIRECTLY - UNLESS YOU KNOW WHAT YOU ARE DOING

user node[:maven][:user] do
  action :create
  supports :manage_home => true
  home "/home/#{node[:maven][:user]}"
  shell "/bin/bash"
  not_if "getent passwd #{node[:maven]['user']}"
end

group node[:maven][:group] do
  action :modify
  members ["#{node[:maven][:user]}"]
  append true
end


private_ip = my_private_ip()
public_ip = my_public_ip()



# Pre-Experiment Code


# Configuration Files
